const data={
  ibadah:{title:"🕌 Ibadah",sub:"5 നമസ്കാരങ്ങൾ + തഹജ്ജുദ്",items:["തഹജ്ജുദ്","സുബ്ഹി","ളുഹർ","അസർ","മഗ്‌രിബ്","ഇശാ","ഖുർആൻ പാരായണം"]},
  study:{title:"📚 Study",sub:"മദ്റസ • സ്കൂൾ",items:["മദ്റസ പാഠ പഠനം","മദ്റസ Homework പൂർത്തിയാക്കി","സ്കൂൾ പാഠ പഠനം","School Homework പൂർത്തിയാക്കി","ഇന്നത്തെ പഠനം Revision"]},
  character:{title:"🌿 Character",sub:"സ്വഭാവം • കുടുംബം",items:["മാതാപിതാക്കളെ സഹായിച്ചു","മാതാപിതാക്കളോട് നല്ല പെരുമാറ്റം","ഉസ്താദിനോടും അധ്യാപകരോടും ആദരം","കള്ളം പറയാതിരിക്കാൻ ശ്രദ്ധിച്ചു","കോപം നിയന്ത്രിച്ചു"]},
  health:{title:"🏃 Health",sub:"ശരീരം • ഉറക്കം",items:["20–30 മിനിറ്റ് Physical Activity","ആവശ്യത്തിന് വെള്ളം കുടിച്ചു","ആരോഗ്യകരമായ ഭക്ഷണം","സമയത്ത് ഉറങ്ങി"]},
  digital:{title:"📱 Digital Discipline",sub:"Mobile • Games",items:["ഉറങ്ങുന്നതിന് മുമ്പ് mobile ഒഴിവാക്കി"],special:true}
};
let state={}; Object.keys(data).forEach(k=>state[k]=data[k].items.map(()=>false));
function render(){const root=document.getElementById("habitGrid");root.innerHTML="";
Object.entries(data).forEach(([g,v])=>{const box=document.createElement("div");box.className="habit-card";box.innerHTML=`<div class="habit-title"><span class="ico">${v.title.split(" ")[0]}</span><div><h3>${v.title.substring(v.title.indexOf(" ")+1)}</h3><small>${v.sub}</small></div></div>`;
v.items.forEach((name,i)=>{const row=document.createElement("div");row.className="habit";if(g==="digital"&&name.includes("mobile")){row.innerHTML=`<label>${name}</label><input class="timebox" id="mobileTime" type="number" min="0" placeholder="min">`}else{row.innerHTML=`<label>${name}</label><button class="check ${state[g][i]?"on":""}" onclick="toggle('${g}',${i},this)">${state[g][i]?"✓":""}</button>`}box.appendChild(row)});
if(g==="digital"){let row=document.createElement("div");row.className="habit";row.innerHTML=`<label>Games സമയം (മിനിറ്റ്)</label><input class="timebox" id="gamesTime" type="number" min="0" placeholder="min">`;box.appendChild(row)}
root.appendChild(box)})}
function toggle(g,i,b){state[g][i]=!state[g][i];b.classList.toggle("on",state[g][i]);b.textContent=state[g][i]?"✓":"";update()}
function pct(g){return Math.round(state[g].filter(Boolean).length/state[g].length*100)}
function update(){let p={ibadah:pct("ibadah"),study:pct("study"),character:pct("character"),health:pct("health")};Object.entries(p).forEach(([g,v])=>{document.getElementById(g+"Pct").textContent=v+"%";document.getElementById(g+"Bar").style.width=v+"%"});let dig=state.digital[0]?100:0;let vals=[...Object.values(p),dig];let overall=Math.round(vals.reduce((a,b)=>a+b,0)/vals.length);document.getElementById("overall").textContent=overall+"%";return {p,dig,overall}}
function today(){return new Date().toISOString().slice(0,10)}
function payload(){let u=document.getElementById("studentId").value.trim()||"STU001", x=update();return {action:"save",studentId:u,date:today(),ibadah:state.ibadah,study:state.study,character:state.character,health:state.health,digital:state.digital,madrasaHomework:!!state.study[1],schoolHomework:!!state.study[3],mobileMinutes:+(document.getElementById("mobileTime")?.value||0),gamesMinutes:+(document.getElementById("gamesTime")?.value||0),overall:x.overall}}
async function api(body){if(!API_URL||API_URL.includes("PASTE_"))throw new Error("API_URL set ചെയ്തിട്ടില്ല");let r=await fetch(API_URL,{method:"POST",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify(body)});return await r.json()}
async function save(){let s=document.getElementById("saveStatus");s.textContent="Saving…";try{let r=await api(payload());s.textContent=r.ok?"✓ Google Sheet-ൽ save ചെയ്തു.":"Save failed";}catch(e){s.textContent="⚠️ "+e.message+" — config.js പരിശോധിക്കുക."}}
async function parentLoad(){let id=document.getElementById("parentStudentId").value.trim();let box=document.getElementById("parentCards");box.innerHTML='<div class="card">Loading…</div>';try{let r=await api({action:"student",studentId:id});if(!r.ok)throw Error(r.error||"No data");let d=r.data||[];let latest=d[d.length-1]||{};box.innerHTML=[["Overall",latest.overall||0],["Qur'an",Math.round((latest.ibadahScore||0))],["Salah",latest.salahScore||0],["Study",latest.studyScore||0]].map(x=>`<div class="metriccard"><span class="small">${x[0]}</span><b>${x[1]}%</b></div>`).join("");drawChart(d.slice(-7))}catch(e){box.innerHTML=`<div class="card">⚠️ ${e.message}</div>`}}
function drawChart(rows){let c=document.getElementById("weeklyChart");if(!rows.length){c.innerHTML="<span class='small'>No weekly data yet.</span>";return}c.innerHTML=rows.map(r=>{let v=+r.overall||0;return `<div class="daybar"><i style="height:${Math.max(8,v*1.45)}px"></i>${String(r.date||"").slice(5)}</div>`}).join("")}
async function adminLoad(){let el=document.getElementById("studentTable"),st=document.getElementById("adminStats");el.innerHTML="Loading…";try{let r=await api({action:"all"});if(!r.ok)throw Error(r.error);let d=r.data||[];let unique=[...new Set(d.map(x=>x.studentId))];let avg=unique.length?Math.round(unique.map(id=>{let a=d.filter(x=>x.studentId===id);return +a[a.length-1].overall||0}).reduce((a,b)=>a+b,0)/unique.length):0;st.innerHTML=[["Students",unique.length],["Records",d.length],["Class Growth",avg+"%"],["Today",d.filter(x=>x.date===today()).length]].map(x=>`<div class="stat"><span>${x[0]}</span><b>${x[1]}</b></div>`).join("");el.innerHTML='<div class="student-row head"><span>Student</span><span>Growth</span><span>Study</span><span>Status</span></div>'+unique.map(id=>{let a=d.filter(x=>x.studentId===id),x=a[a.length-1]||{};let v=+x.overall||0;return `<div class="student-row"><span>${id}</span><span>${v}%</span><span>${x.studyScore||0}%</span><span class="status ${v>=80?"green":v>=60?"orange":"red"}">${v>=80?"On track":v>=60?"Improve":"Needs attention"}</span></div>`}).join("")}catch(e){el.textContent="⚠️ "+e.message}}
function tabs(){document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));b.classList.add("active");document.querySelectorAll(".view").forEach(v=>v.classList.add("hidden"));document.getElementById(b.dataset.tab).classList.remove("hidden")})}
function toggleTheme(){document.body.classList.toggle("dark")}
document.getElementById("today").textContent=new Date().toLocaleDateString("en-IN",{day:"2-digit",month:"short",year:"numeric"});
document.getElementById("saveBtn").onclick=save;document.getElementById("parentLoad").onclick=parentLoad;document.getElementById("adminLoad").onclick=adminLoad;document.getElementById("loadBtn").onclick=()=>{state=JSON.parse(JSON.stringify(Object.fromEntries(Object.entries(data).map(([k,v])=>[k,v.items.map(()=>false)]))));render();update()};tabs();render();update();